server:
  port: 8080
spring:
  application:
    name: spring-config-client
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:8090"
  cloud:
    config: # Ex) `http://localhost:8090/config/test`
      name: config # config name
      profile: dev # config profile
management:
  endpoints:
    web:
      exposure:
        include: refresh
message:
  one: one
  two: two